alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias ll='ls --color=always -l -h'
alias la='ls --color=always -A'
alias l='ls --color=always -CF'
alias asearch='apt-cache search'
alias ashow='apt-cache show'
alias h='history'
alias nn='nano -c'
alias cl='clear'
alias grep='grep --color=auto'
alias i='sudo ag install'
alias ip='ip --color=auto'
alias u='sudo apt-get update'
alias up='sudo apt-get upgrade'
alias upp='sudo apt-get update -y && sudo apt-get upgrade -y'
alias uppr='sudo apt-get update -y && sudo apt-get dist-upgrade -y'
alias x='exit'
alias xx='sudo shutdown now'
alias xwx='sudo poweroff'
alias spyme='sudo lnav /var/log/syslog /var/log/auth.log'
alias sysupdate='sudo sysupdate'
alias bat='bat -pp'
alias free='free -ht'
alias showshortcut='dconf dump /org/gnome/settings-daemon/plugins/media-keys/'
alias sshuttle='sudo sshuttle'
